# Weather Australia Kaggle
       #####################################################
####################### @author:Birbal Srivastava ############################
       #####################################################
    

import numpy as np
import pandas as pd

In [21]:
df = pd.read_csv("weatherAUS.csv")
print("Size of weather dataframe : ",df.shape)

Size of weather dataframe :  (142193, 24)


In [22]:
print(df[0:10])

         Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  2008-12-01   Albury     13.4     22.9       0.6          NaN       NaN   
1  2008-12-02   Albury      7.4     25.1       0.0          NaN       NaN   
2  2008-12-03   Albury     12.9     25.7       0.0          NaN       NaN   
3  2008-12-04   Albury      9.2     28.0       0.0          NaN       NaN   
4  2008-12-05   Albury     17.5     32.3       1.0          NaN       NaN   
5  2008-12-06   Albury     14.6     29.7       0.2          NaN       NaN   
6  2008-12-07   Albury     14.3     25.0       0.0          NaN       NaN   
7  2008-12-08   Albury      7.7     26.7       0.0          NaN       NaN   
8  2008-12-09   Albury      9.7     31.9       0.0          NaN       NaN   
9  2008-12-10   Albury     13.1     30.1       1.4          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am  ... Humidity3pm  Pressure9am  \
0           W           44.0          W  ...        22.0       1007.7   
1     

# Data Preprocessing

In [19]:
# Check for null values
print(df.count().sort_values())

Sunshine          74377
Evaporation       81350
Cloud3pm          85099
Cloud9am          88536
Pressure9am      128179
Pressure3pm      128212
WindDir9am       132180
WindGustDir      132863
WindGustSpeed    132923
WindDir3pm       138415
Humidity3pm      138583
Temp3pm          139467
WindSpeed3pm     139563
Humidity9am      140419
RainToday        140787
Rainfall         140787
WindSpeed9am     140845
Temp9am          141289
MinTemp          141556
MaxTemp          141871
Date             142193
Location         142193
RISK_MM          142193
RainTomorrow     142193
dtype: int64


In [7]:
count_nan = len(df) - df.count()
print(count_nan)

Date                 0
Location             0
MinTemp            637
MaxTemp            322
Rainfall          1406
Evaporation      60843
Sunshine         67816
WindGustDir       9330
WindGustSpeed     9270
WindDir9am       10013
WindDir3pm        3778
WindSpeed9am      1348
WindSpeed3pm      2630
Humidity9am       1774
Humidity3pm       3610
Pressure9am      14014
Pressure3pm      13981
Cloud9am         53657
Cloud3pm         57094
Temp9am            904
Temp3pm           2726
RainToday         1406
RISK_MM              0
RainTomorrow         0
dtype: int64


In [9]:
df.isnull().sum(axis=0)

Date                 0
Location             0
MinTemp            637
MaxTemp            322
Rainfall          1406
Evaporation      60843
Sunshine         67816
WindGustDir       9330
WindGustSpeed     9270
WindDir9am       10013
WindDir3pm        3778
WindSpeed9am      1348
WindSpeed3pm      2630
Humidity9am       1774
Humidity3pm       3610
Pressure9am      14014
Pressure3pm      13981
Cloud9am         53657
Cloud3pm         57094
Temp9am            904
Temp3pm           2726
RainToday         1406
RISK_MM              0
RainTomorrow         0
dtype: int64

### Remove unnecessary columns

In [23]:
df = df.drop(columns = ["Sunshine", "Evaporation", "Cloud3pm", "Cloud9am", "Location", "Date","RISK_MM"], axis=1)

In [24]:
print(len(df)-df.count())

MinTemp            637
MaxTemp            322
Rainfall          1406
WindGustDir       9330
WindGustSpeed     9270
WindDir9am       10013
WindDir3pm        3778
WindSpeed9am      1348
WindSpeed3pm      2630
Humidity9am       1774
Humidity3pm       3610
Pressure9am      14014
Pressure3pm      13981
Temp9am            904
Temp3pm           2726
RainToday         1406
RainTomorrow         0
dtype: int64


In [28]:
df.count().sort_values()
print(df.shape)

(112925, 17)


In [25]:
df = df.dropna(how = "any")

# Remove Outliers

In [29]:
from scipy import stats
z = np.abs(stats.zscore(df._get_numeric_data()))
print(z)
df = df[(z < 3).all(axis=1)]
print(df.shape)

[[0.11756741 0.10822071 0.20666127 ... 1.14245477 0.08843526 0.04787026]
 [0.84180219 0.20684494 0.27640495 ... 1.04184813 0.04122846 0.31776848]
 [0.03761995 0.29277194 0.27640495 ... 0.91249673 0.55672435 0.15688743]
 ...
 [1.44940294 0.23548728 0.27640495 ... 0.58223051 1.03257127 0.34701958]
 [1.16159206 0.46462594 0.27640495 ... 0.25166583 0.78080166 0.58102838]
 [0.77784422 0.4789471  0.27640495 ... 0.2085487  0.37167606 0.56640283]]
(107868, 17)


In [30]:
df.head()

MinTemp  MaxTemp  Rainfall WindGustDir  WindGustSpeed WindDir9am  \
0     13.4     22.9       0.6           W           44.0          W   
1      7.4     25.1       0.0         WNW           44.0        NNW   
2     12.9     25.7       0.0         WSW           46.0          W   
3      9.2     28.0       0.0          NE           24.0         SE   
4     17.5     32.3       1.0           W           41.0        ENE   

  WindDir3pm  WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  \
0        WNW          20.0          24.0         71.0         22.0   
1        WSW           4.0          22.0         44.0         25.0   
2        WSW          19.0          26.0         38.0         30.0   
3          E          11.0           9.0         45.0         16.0   
4         NW           7.0          20.0         82.0         33.0   

   Pressure9am  Pressure3pm  Temp9am  Temp3pm RainToday RainTomorrow  
0       1007.7       1007.1     16.9     21.8        No           No  
1       1010.6       1007.8     17.2     24.3        No           No  
2       1007.6       1008.7     21.0     23.2        No           No  
3       1017.6       1012.8     18.1     26.5        No           No  
4       1010.8       1006.0     17.8     29.7        No           No

In [32]:
df['RainToday'].replace({'No':0,'Yes':1}, inplace = True)

In [33]:
df['RainTomorrow'].replace({'No':0, 'Yes': 1}, inplace = True)

In [35]:
categorical_columns = ['WindGustDir', 'WindDir9am', 'WindDir3pm' ]
for col in categorical_columns:
    print(col,':',np.unique(df[col]))

WindGustDir : ['E' 'ENE' 'ESE' 'N' 'NE' 'NNE' 'NNW' 'NW' 'S' 'SE' 'SSE' 'SSW' 'SW' 'W'
 'WNW' 'WSW']
WindDir9am : ['E' 'ENE' 'ESE' 'N' 'NE' 'NNE' 'NNW' 'NW' 'S' 'SE' 'SSE' 'SSW' 'SW' 'W'
 'WNW' 'WSW']
WindDir3pm : ['E' 'ENE' 'ESE' 'N' 'NE' 'NNE' 'NNW' 'NW' 'S' 'SE' 'SSE' 'SSW' 'SW' 'W'
 'WNW' 'WSW']


In [36]:
df = pd.get_dummies(df, columns=categorical_columns)
print(df.iloc[4:9])

   MinTemp  MaxTemp  Rainfall  WindGustSpeed  WindSpeed9am  WindSpeed3pm  \
4     17.5     32.3       1.0           41.0           7.0          20.0   
5     14.6     29.7       0.2           56.0          19.0          24.0   
6     14.3     25.0       0.0           50.0          20.0          24.0   
7      7.7     26.7       0.0           35.0           6.0          17.0   
8      9.7     31.9       0.0           80.0           7.0          28.0   

   Humidity9am  Humidity3pm  Pressure9am  Pressure3pm  ...  WindDir3pm_NNW  \
4         82.0         33.0       1010.8       1006.0  ...               0   
5         55.0         23.0       1009.2       1005.4  ...               0   
6         49.0         19.0       1009.6       1008.2  ...               0   
7         48.0         19.0       1013.4       1010.1  ...               0   
8         42.0          9.0       1008.9       1003.6  ...               0   

   WindDir3pm_NW  WindDir3pm_S  WindDir3pm_SE  WindDir3pm_SSE  WindDir3pm_

# Normalizing dataset

In [38]:
from sklearn import preprocessing
scaler = preprocessing.MinMaxScaler()
scaler.fit(df)
df = pd.DataFrame(scaler.transform(df), index = df.index, columns = df.columns)
print(df.iloc[4:10])

    MinTemp   MaxTemp  Rainfall  WindGustSpeed  WindSpeed9am  WindSpeed3pm  \
4  0.628342  0.696296  0.035714       0.465753      0.135135      0.428571   
5  0.550802  0.632099  0.007143       0.671233      0.459459      0.523810   
6  0.542781  0.516049  0.000000       0.589041      0.486486      0.523810   
7  0.366310  0.558025  0.000000       0.383562      0.108108      0.357143   
8  0.419786  0.686420  0.000000       1.000000      0.135135      0.619048   
9  0.510695  0.641975  0.050000       0.287671      0.351351      0.214286   

   Humidity9am  Humidity3pm  Pressure9am  Pressure3pm  ...  WindDir3pm_NNW  \
4     0.797753         0.33     0.342043     0.282974  ...             0.0   
5     0.494382         0.23     0.304038     0.268585  ...             0.0   
6     0.426966         0.19     0.313539     0.335731  ...             0.0   
7     0.415730         0.19     0.403800     0.381295  ...             0.0   
8     0.348315         0.09     0.296912     0.225420  ...     

# Exploratory Data Analysis

In [46]:
from sklearn.feature_selection import SelectKBest, chi2
X = df.iloc[:, df.columns!='RainTomorrow']
y = df[['RainTomorrow']]
selector = SelectKBest(chi2, k=3)
selector.fit(X,y)

SelectKBest(k=3, score_func=<function chi2 at 0x11fa1b840>)

In [47]:
X_new = selector.transform(X)

/Users/birbalsrivastava/anaconda/lib/python3.6/site-packages/sklearn/utils/__init__.py:54: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(mask.dtype, np.int):


In [48]:
print(X.columns[selector.get_support(indices=True)])

Index(['Rainfall', 'Humidity3pm', 'RainToday'], dtype='object')


In [49]:
X = df[['Rainfall','Humidity3pm','RainToday']]
y = df[['RainTomorrow']]

# Data Modelling

In [51]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import time

In [52]:
t0 = time.time()

In [53]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)
clf_logistic_regression = LogisticRegression(random_state=0)
clf_logistic_regression.fit(X_train, y_train)

/Users/birbalsrivastava/anaconda/lib/python3.6/site-packages/sklearn/utils/validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [56]:
y_pred = clf_logistic_regression.predict(X_test)
score = accuracy_score(y_test, y_pred)
print("Accuracy using logistic regression: ", score)
print("Time taken using logistic regression: ",time.time()-t0)

Accuracy using logistic regression:  0.8427428077006273
Time taken using logistic regression:  343.72815108299255


## Ensemble models

In [58]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
t0=time.time()

In [61]:
# Data slicing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
clf_rf = RandomForestClassifier(n_estimators=100, max_depth=4, random_state=0)
clf_rf.fit(X_train, y_train)

/Users/birbalsrivastava/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=4, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=100, n_jobs=1, oob_score=False, random_state=0,
            verbose=0, warm_start=False)

In [62]:
y_pred = clf_rf.predict(X_test)
score = accuracy_score(y_test, y_pred)
print("Accuracy using random forest classifier: ", score)
print("Time taken using random forest classifier: ",time.time()-t0)

Accuracy using random forest classifier:  0.8384166125892277
Time taken using random forest classifier:  232.70560479164124
